#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(cd "$script_dir/.." && pwd)
deployment_root=$(cd "$repo_root/.." && pwd)
environment_file=${PFT_TRAIN_ENV_FILE:-$deployment_root/training.env}

if [[ -f "$environment_file" ]]; then
    # The environment file is generated by start_vton_training_remote.sh.
    # shellcheck disable=SC1090
    source "$environment_file"
fi

venv_path=${PFT_VENV:-/venv/main}
if [[ ! -f "$venv_path/bin/activate" ]]; then
    echo "Python environment not found: $venv_path" >&2
    exit 1
fi
# shellcheck disable=SC1091
source "$venv_path/bin/activate"

export VITONHD_ROOT=${VITONHD_ROOT:-$deployment_root/high-resolution-viton-zalando-dataset}
export VITONHD_SMOKE_DIR=${VITONHD_SMOKE_DIR:-$VITONHD_ROOT/smoke32}
export PFT_XL_CKPT=${PFT_XL_CKPT:-$repo_root/checkpoints/pft-xl_step400k_ema.ckpt}

experiment=${PFT_EXPERIMENT:-viton-pft-xl-smoke16gb}
extra_arguments=()
if [[ -n ${PFT_TRAIN_OVERRIDES:-} ]]; then
    read -r -a extra_arguments <<< "$PFT_TRAIN_OVERRIDES"
fi

cd "$repo_root"
exec python -u train.py "experiment=$experiment" "${extra_arguments[@]}"

